FROM ruby:3.4.10

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    postgresql-client \
    vim \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Gemfile ./
COPY Gemfile.lock ./
RUN bundle install

COPY . .

CMD ["bin/rails","server","-b","0.0.0.0"]